modLoader="javafml"
license="custom"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/BobMowzie/MowziesMobs/issues"
[[mods]]
    modId="mowziesmobs"
    version="1.2.25"
    displayName="Mowzie's Mobs"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs"
    authors="BobMowzie, pau101"
    description="Mowzie's Mobs adds a variety of high-quality fantasy creatures to your Minecraft world."
    logoFile="banner.png"
[[dependencies.mowziesmobs]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mowziesmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mowziesmobs]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.10,)"
    ordering="BEFORE"
    side="BOTH"